// 課程清單 —— 單一事實來源。加一課：這裡加一筆 + 開一個 lessons/<id>/ 資料夾。
// status: 'ready' 可點進去；'planned' 在目錄顯示為灰底「規劃中」、還沒做。
// part: 篇名。同一篇連續排在一起，換篇時目錄與抽屜會插一條分隔標題。
export const LESSONS = [
  {
    id: '01-boids',
    title: '第 1 課 · Boids 三規則',
    blurb: '分離／對齊／聚合——沒有指揮官的群飛，整群卻像一個生命體。',
    status: 'ready',
    part: '基礎篇',
  },
  {
    id: '02-decentralized',
    title: '第 2 課 · 去中心化 vs 中央控制',
    blurb: '把「有老大」和「沒老大」擺在一起斬首，看誰先垮。',
    status: 'ready',
    part: '基礎篇',
  },
  {
    id: '03-broken-comms',
    title: '第 3 課 · 斷通訊還能協同嗎',
    blurb: '剪掉通訊半徑、加上封包遺失，看群體在哪一刻碎成孤島。',
    status: 'ready',
    part: '基礎篇',
  },
  {
    id: '04-scaling',
    title: '第 4 課 · 從 10 隻到 2000 隻',
    blurb: '同一套規則，數量放大百倍。行為還在嗎？電腦撐得住嗎？',
    status: 'ready',
    part: '基礎篇',
  },
  {
    id: '05-sensing',
    title: '第 5 課 · 分散式感知',
    blurb: '每隻只看得到一點點，合起來卻能把整片戰場掃乾淨。',
    status: 'ready',
    part: '基礎篇',
  },
  {
    id: '06-consensus',
    title: '第 6 課 · 群體共識',
    blurb: '蜜蜂怎麼不靠老大，全群選定同一個新家。',
    status: 'ready',
    part: '基礎篇',
  },
  {
    id: '07-stigmergy',
    title: '第 7 課 · 費洛蒙與自組織分工',
    blurb: '螞蟻不留訊息給彼此，只改環境——最短路徑自己浮現。',
    status: 'ready',
    part: '基礎篇',
  },
  {
    id: '08-resilience',
    title: '第 8 課 · 抗毀韌性',
    blurb: '打掉一半個體，剩下的自己補位、重新蓋滿空缺。',
    status: 'ready',
    part: '基礎篇',
  },
  {
    id: '09-human-loop',
    title: '第 9 課 · 人在環路',
    blurb: '自主歸自主，人類在哪一格按下同意？畫出不可逾越的線。',
    status: 'ready',
    part: '基礎篇',
  },
  {
    id: '10-sandbox',
    title: '第 10 課 · 綜合沙盒',
    blurb: '把前九課的規則全丟進同一個場：放障礙、放掠食者、自己玩。',
    status: 'ready',
    part: '基礎篇',
  },
  {
    id: '11-sync',
    title: '第 11 課 · 螢火蟲同步',
    blurb: '沒有共同時鐘，幾千隻卻閃成同一拍——只因為「看到旁邊閃就提早一點」。',
    status: 'ready',
    part: '進階篇',
  },
  {
    id: '12-informed-few',
    title: '第 12 課 · 少數知情者領路',
    blurb: '只有 5% 知道要去哪，沒人喊口令，整群卻走對了。',
    status: 'ready',
    part: '進階篇',
  },
  {
    id: '13-byzantine',
    title: '第 13 課 · 群裡混進叛徒',
    blurb: '3% 回報假值，用平均整群就被帶走；換成中位數，硬是不動。',
    status: 'ready',
    part: '進階篇',
  },
  {
    id: '14-self-assembly',
    title: '第 14 課 · 自組裝隊形',
    blurb: '沒有藍圖分派、沒人知道自己該站哪——形狀自己長出來。',
    status: 'ready',
    part: '進階篇',
  },
  {
    id: '15-topological',
    title: '第 15 課 · 鄰居是「幾隻」不是「幾公尺」',
    blurb: '椋鳥只跟最近的六七隻互動——換一種鄰居定義，整群散不散的結局就反過來。',
    status: 'ready',
    part: '群體物理篇',
  },
  {
    id: '16-order-parameter',
    title: '第 16 課 · 秩序參數與臨界雜訊',
    blurb: '把整群的整齊度壓成一個數字，再轉動雜訊旋鈕——它不是慢慢變亂，是啪一下垮掉。',
    status: 'ready',
    part: '群體物理篇',
  },
  {
    id: '17-lane-formation',
    title: '第 17 課 · 人流自己分出車道',
    blurb: '兩股人相向而行，沒人畫線、沒人指揮，擠到一個程度車道自己浮出來。',
    status: 'ready',
    part: '群體物理篇',
  },
  {
    id: '18-locust-phase',
    title: '第 18 課 · 蝗蟲的密度門檻',
    blurb: '每隻蝗蟲的規則從頭到尾沒變，只是擠得比較近——整群就從亂走變成同向行軍。',
    status: 'ready',
    part: '群體物理篇',
  },
  {
    id: '19-collision-avoidance',
    title: '第 19 課 · 把會撞的速度先劃掉',
    blurb: '避碰不是看到就閃——是先算出「哪些速度會撞」，全部劃掉，剩下的隨便挑都安全。',
    status: 'ready',
    part: '工程應用篇',
  },
  {
    id: '20-coverage-control',
    title: '第 20 課 · 一群機器人怎麼把一片地分完',
    blurb: '每個地方歸最近的那台管，每台往自己那塊地的重心走——沒有人分配，站位自己長出來。',
    status: 'ready',
    part: '工程應用篇',
  },
  {
    id: '21-task-auction',
    title: '第 21 課 · 沒有指揮，用喊價分工',
    blurb: '各搶最近的會撞在一起、還有人閒著。改成喊價，價格自己把人推到該去的地方。',
    status: 'ready',
    part: '工程應用篇',
  },
  {
    id: '22-pso',
    title: '第 22 課 · 群飛規則拿來解題',
    blurb: '把鳥群模擬裡的棲地拿掉，改成「誰站的位置比較好就往那靠」——鳥群變成了搜尋器。',
    status: 'ready',
    part: '工程應用篇',
  },
  {
    id: '23-shepherding',
    title: '第 23 課 · 一隻怎麼推得動一群',
    blurb: '牧羊犬只有兩條規則和一個切換條件，就把一整群不聽話的羊推進了圈。',
    status: 'ready',
    part: '工程應用篇',
  },
  {
    id: '24-startle-cascade',
    title: '第 24 課 · 一隻嚇到，整群跟著跑',
    blurb: '中間沒有一隻看到那個影子。訊息是靠「誰在誰的視野裡佔得夠大」一層層接出去的。',
    status: 'ready',
    part: '群體認知篇',
  },
  {
    id: '25-many-wrongs',
    title: '第 25 課 · 一群爛導航員，平均起來很準',
    blurb: '每一隻的羅盤都歪，合起來那條線卻比任何一隻都準——但有一種歪法平均不掉。',
    status: 'ready',
    part: '群體認知篇',
  },
  {
    id: '26-collective-memory',
    title: '第 26 課 · 同樣的規則，群體記得自己來過哪',
    blurb: '把旋鈕轉上去再轉回同一格，群體停在不同的形狀——它記得自己是從哪邊來的。',
    status: 'ready',
    part: '群體認知篇',
  },
];

// 每一篇的一句話導言：目錄與抽屜的篇名底下各印一行，
// 讓讀者在點進任何一課之前，先知道這一篇要回答什麼問題。
// 沒有寫在這裡的篇名就只印標題，加新篇忘了補也不會壞。
export const PART_INTROS = {
  '基礎篇': '從「沒有指揮官也能成群」開始，一路走到可以自己玩的綜合沙盒。',
  '進階篇': '拆掉基礎篇沒說破的四個假設：同一個節拍、大家都知道要去哪、沒有人說謊、有人分派座位。',
  '群體物理篇': '換成物理學家的問法——這些行為什麼時候出現、什麼時候突然消失，以及門檻在哪。',
  '工程應用篇': '把前面的原理接到真的在用的做法：避碰、站位、分工、解題，以及從外面推動一整群。',
  '群體認知篇': '群體怎麼把訊息傳出去、怎麼把誤差平均掉，以及怎麼記住自己來過哪。',
};
